Controllers
M2htechnologies/event_managment_api pull request #3
Opened 2024-08-12 16:12 UTC by raffay0shahzad

all previous PR changes resolved except const msgs

2024-08-12 17:37 UTC, ShanCoder110 requested changes

2024-08-12 17:37 UTC, ShanCoder110 commented on controllers/authController.js
> +            error: "All fields are required. Please provide valid values for each field.",
Write short message + change key error to message

2024-08-12 17:37 UTC, ShanCoder110 commented on controllers/authController.js
> +
Wrap it in try catch

2024-08-12 17:37 UTC, ShanCoder110 commented on controllers/authController.js
> +
Use standard spacing (i think prettier is not doing its job:))

2024-08-12 17:37 UTC, ShanCoder110 commented on controllers/authController.js
> +            error: "All fields are required. Please provide valid values for each field.",
Same as above

2024-08-12 17:37 UTC, ShanCoder110 commented on controllers/ticketController.js
> +            eventId,
It would be better to use convention like eventId as event and userId as  use because we will population when we make get api and and populate it as we name it eventId then it will be like
eventId.name 
If we name it event then simply when we populate it it will be like
event.name

2024-08-12 17:37 UTC, ShanCoder110 commented on controllers/ticketController.js
> +            return res.status(400).json({
Use db required type for validation or move validation in separate validators folder and in that ticketValidators.js

2024-08-12 17:37 UTC, ShanCoder110 commented on controllers/ticketController.js
> +                error: "All fields are required. Please provide valid values for each field.",
Short message

2024-08-12 17:37 UTC, ShanCoder110 commented on controllers/ticketController.js
> +            eventId,
We can use Ticket.create({}) this syntex too (suggestion)

2024-08-12 17:37 UTC, ShanCoder110 commented on controllers/ticketController.js
> +export const getTickets = async (req, res, next) => {
If you want to get all tickets then name controller as getAllTickets to be clearfield in future

2024-08-12 17:37 UTC, ShanCoder110 commented on controllers/ticketController.js
> +export const getTicketsForEvent = async (req, res) => {
We can make it as one controller in getAllTickets use query to get event tickets and to get all tickets no need to make this controller

2024-08-12 17:37 UTC, ShanCoder110 commented on controllers/ticketController.js
> +    const tickets = await ticket.find({ eventId }).populate("eventId").populate("userId");
Only populate those fields which we require to get better response rate

2024-08-12 17:37 UTC, ShanCoder110 commented on index.js
> +});
Eol missing

2024-08-12 17:37 UTC, ShanCoder110 commented on middleware/cloudinaryMiddleware.js
> +    if (typeof(eventPic) !== "string") {
Check if event image exists string can be empty and it must start with how base64 image string starts with

2024-08-12 17:37 UTC, ShanCoder110 commented on routes/event.js
>  const router = express.Router();
We can create route as
router.post("/",controller).get("/",controller)
router.patch("/:id"). delete ("/:id")

2024-08-12 17:37 UTC, ShanCoder110 commented on utils/mongoConfig.js
> +export default connectDB;
Eol missing

2024-08-13 16:04 UTC, raffay0shahzad commented
Pushed recent code to the controllers branch.
Kindly review

2024-08-13 16:33 UTC, ShanCoder110 requested changes

2024-08-13 16:33 UTC, ShanCoder110 commented on controllers/invoiceController.js
> +        success_url: `https://www.google.com`,
Don't hard code urls store it in env

2024-08-13 16:33 UTC, ShanCoder110 commented on controllers/invoiceController.js
> +      const invoice = await Invoice.findById(req.params.id);
Destruct param from req.params 
As
Const {id} =req.params

2024-08-13 16:33 UTC, ShanCoder110 commented on controllers/webhookController.js
> +        //console.log(event.data.object);
Remove console

2024-08-13 16:33 UTC, ShanCoder110 commented on controllers/webhookController.js
> +        console.log(`Unhandled event type ${event.type}`);
Remove console

2024-08-13 16:33 UTC, ShanCoder110 commented on controllers/webhookController.js
> +
Eol missing

2024-08-13 16:33 UTC, ShanCoder110 commented on models/cartModel.js
> +    ref: 'User',
Remove this model if not used

2024-08-14 06:15 UTC, ShanCoder110 approved these changes
Looks good to me

2024-08-14 06:30 UTC, merged